export const SET_USER_REQUEST = "SET_USER_REQUEST"
export const SET_USER_SUCCESS = "SET_USER_SUCCESS"
export const SET_USER_FAIL = "SET_USER_FAIL"


export const SET_PLAYLIST_REQUEST = "SET_PLAYLIST_REQUEST"
export const SET_PLAYLIST_SUCCESS = "SET_PLAYLIST_SUCCESS"
export const SET_PLAYLIST_FAIL = "SET_PLAYLIST_FAIL"

export const SET_PLAYERSTATE_REQUEST = "SET_PLAYERSTATE_REQUEST"
export const SET_PLAYERSTATE_SUCCESS = "SET_PLAYERSTATE_SUCCESS"
export const SET_PLAYERSTATE_FAIL = "SET_PLAYERSTATE_FAIL"

export const SET_ACTIVE_DEVICES_REQUEST = "SET_ACTIVE_DEVICES_REQUEST"
export const SET_ACTIVE_DEVICES_SUCCESS = "SET_ACTIVE_DEVICES_SUCCESS"

export const SET_TRACT_STATE = "SET_TRACT_STATE"
export const SET_PLAYING = "SET_PLAYING"
export const SET_TRACKS = "SET_TRACKS"

export const SET_REPEAT_MODE = "SET_REPEAT_MODE"

export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS"

export const SET_ACTIVE_DEVICE = "SET_ACTIVE_DEVICE"

export const SET_RECENT_TRACKS = "SET_RECENT_TRACKS"

export const SET_TOKEN = "SET_TOKEN"
export const SET_PLAYLIST_ID  = "SET_PLAYLIST_ID"